### ISSUE TITLE
Docker images include Elixir source

### ISSUE THREAD

**Issue by jonatanklosko** [erlef/docker-elixir#13]
The images should really only include the compiled Elixir modules, but currently all of the source code is there. This is how to verify that:

```
➜  ~ docker run -it elixir:1.11.3-alpine /bin/sh
/ # ls /usr/local/src/elixir/lib/elixir/lib/
access.ex              collectable.ex         gen_event.ex           list                   process.ex             string_io.ex
agent                  config                 gen_server.ex          list.ex                protocol.ex            supervisor
agent.ex               config.ex              hash_dict.ex           macro                  range.ex               supervisor.ex
application.ex         dict.ex                hash_set.ex            macro.ex               record                 system.ex
atom.ex                dynamic_supervisor.ex  inspect                map.ex                 record.ex              task
base.ex                enum.ex                inspect.ex             map_set.ex             regex.ex               task.ex
behaviour.ex           exception.ex           integer.ex             module                 registry.ex            tuple.ex
bitwise.ex             file                   io                     module.ex              set.ex                 uri.ex
calendar               file.ex                io.ex                  node.ex                stream                 version.ex
calendar.ex            float.ex               kernel                 option_parser.ex       stream.ex
code                   function.ex            kernel.ex              path.ex                string
code.ex                gen_event              keyword.ex             port.ex                string.ex
```

In the image definition the source should be removed, or ideally the image could be built using multi-stage builds. For the reference [that's](https://github.com/hexpm/bob/blob/d12d93580216741a396305f0bc89ab73e93c551f/priv/scripts/docker/elixir-alpine.dockerfile#L19-L21) how the hexpm team does it.

**Comment by dolfinus** [comment]
Well, Elixir packages are being downloaded as the source code which is then compiled into a .beam files. Some of packages may depend on Elixir modules source code to be compiled properly, or to be checked with Dialyzer. IMHO, the source code should be left intact.

But the thing I could agree is that there should be no '.github' folder in a `/usr/local/src/elixir` folder as well as some other ones - hidden folders and files which are useful only in the git repo, tests and so on.
I've created #19 to remove them.

**Comment by josevalim** [comment]
We had this discussion for the precompiled Elixir files and we decided to keep the source files. It can be useful in multiple occasions, such as `open` or when debugging from IEx. So I agree with keeping them!

**Comment by jonatanklosko** [comment]
Alright, in that case I'm closing the issue, thanks!
