### ISSUE TITLE
1.12 Alpine Builds Missing Symbols

### ISSUE THREAD

**Issue by mlh758** [erlef/docker-elixir#20]
```
FROM elixir:1.12.1-alpine as builder

WORKDIR /home/builder/build
RUN apk add git
ENV MIX_ENV=prod
RUN mix local.hex --force
RUN mix local.rebar --force
COPY mix.exs mix.lock ./
RUN mix deps.get
RUN mix compile
ADD . .
RUN mix release

FROM alpine:3.13
WORKDIR /var/www/app
COPY --from=builder /home/builder/build/_build/prod/ ./
EXPOSE 4000
ENTRYPOINT [ "/var/www/app/rel/measure_library/bin/app", "start" ]
```

Errors:
```
Error loading shared library libstdc++.so.6: No such file or directory (needed by /var/www/app/rel/app/erts-12.0.2/bin/beam.smp)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /var/www/app/rel/app/erts-12.0.2/bin/beam.smp)
Error relocating /var/www/app/rel/measure_library/erts-12.0.2/bin/beam.smp: __cxa_begin_catch: symbol not found
Error relocating /var/www/app/rel/measure_library/erts-12.0.2/bin/beam.smp: _ZSt24__throw_out_of_range_fmtPKcz: symbol not found
Error relocating /var/www/app/rel/measure_library/erts-12.0.2/bin/beam.smp: _Znwm: symbol not found
Error relocating /var/www/app/rel/measure_library/erts-12.0.2/bin/beam.smp: _ZSt20__throw_length_errorPKc: symbol not found
Error relocating /var/www/app/rel/measure_library/erts-12.0.2/bin/beam.smp: __cxa_guard_release: symbol not found
```

If I change the tag back to elixir:1.11-alpine everything is fine.

**Comment by dolfinus** [comment]
Actually, this is not related to elixir or erlang docker images at all.

Erlang image is installing libgcc and libstdc++ here, to be able to compile .c files of BEAM virtual machine:
https://github.com/erlang/docker-erlang-otp/blob/aa423fb73fe72170fc5d9112ff90a167c696bed3/24/alpine/Dockerfile#L19-L20
Then it is being checked which files are important for BEAM to work properly:
https://github.com/erlang/docker-erlang-otp/blob/aa423fb73fe72170fc5d9112ff90a167c696bed3/24/alpine/Dockerfile#L46
And then these libraries are left intact in the image while other build devs are removed:
https://github.com/erlang/docker-erlang-otp/blob/aa423fb73fe72170fc5d9112ff90a167c696bed3/24/alpine/Dockerfile#L62-L66
![изображение](https://user-images.githubusercontent.com/4661021/121803117-a8678400-cc48-11eb-8948-6973e83871ec.png)

But you're building up release files in the alpine image with libstdc++ and then trying to run it on the bare alpine image with no such packages included.
Your release image should be based or the same elixir or erlang image, or you should install all the packages required by BEAM on top of the alpine image.

**Comment by mlh758** [comment]
So the runtime libraries of the BEAM have changed then with OTP 24? The Elixir 11 images build and run fine this way.

My first instinct with Alpine when I suddenly get missing symbol errors is that something is accidentally using glibc, but I can just start adding libraries to the final container.

**Comment by dolfinus** [comment]
> So the runtime libraries of the BEAM have changed then with OTP 24?
It looks like that. OTP 24 introduced JIT compiler which replaced old HiPE compiler, so it could be not compatible with non-glibc libc implementations like alpine's musl.

**Comment by mlh758** [comment]
Looks like adding `libstdc++` in the final container is enough to satisfy the new runtime dependencies.

Maybe that's worth throwing in the readme?

**Comment by dolfinus** [comment]
Well, you've build an application in a elixir image but them moved it into alpine image. Do you think that this is the common scenario?
Also it does not connected to elixir image, but erlang image.

**Comment by mlh758** [comment]
The elixir image _is_ an Alpine image. It's common for language images to have extra tools and libraries present (like mix and iex) that you don't need to actually run whatever application you've built using those tools. Issues like #19 aren't a problem if you assume the base language image is just for _building_ your app rather than running it.

**Comment by dolfinus** [comment]
But libstd is not an extra tool or mix package that is mandatory for running the application. It is need by Erlang itself to work properly. That's why it is included into the image.

Nobody promised you that executable built on one image will work on another one. There is no such feature described on Elixir or Erlang docker images, both in a repo and Dockerhub Readme. But instead there is a notice:
> so software will often run into issues depending on the depth of their libc requirements/assumptions. See this Hacker News comment thread for more discussion of the issues that might arise and some pro/con comparisons of using Alpine-based images.

If you want to build a really system-independent executable file, you should choose Go, it can be run just on the `scratch` image, no dependencies are need.
Also you can ask if it is possible to enable static linking for Erlang binaries here: https://github.com/erlang/docker-erlang-otp.

But again, there is just nothing related to Elixir.

**Comment by mlh758** [comment]
> libstd is not an extra tool or mix package that is mandatory for running the application. It is need by Erlang itself to work properly

It didn't used to be, and now it is, which is a useful thing to know when upgrading from the 1.11 image. I'm not asking you to change anything in the image, just that it's helpful information to have in the Readme.

> But instead there is a notice:

That's in reference to using stuff built on other Linux distributions. Anything built around glibc is likely to have issues with musl. Building on the elixir alpine image and transferring the compiled asset to a clean alpine image is keeping it in the same distribution. I wouldn't use golang:1-16-buster to build and try to run it on alpine:3.

**Comment by nclark** [comment]
> Well, you've build an application in a elixir image but them moved it into alpine image. Do you think that this is the common scenario?

👋 

I'm in the same predicament, I've been following along here as I haven't found anywhere else this issue is being discussed. I'm not sure that it's a common scenario, but my image ended up here following the "[Deploying with Docker](https://hexdocs.pm/distillery/guides/working_with_docker.html)" section of the distillery README so I cant' imagine @mlh758 and I are the only ones.

Is simply adding libstdc++ back in via apk a good solution here?

**Comment by mlh758** [comment]
@nclark Yes, you'd just need to add libstdc++ in via apk, the Alpine package system does a good job of not bloating the image when you do that. It's a dynamic link so you'll need it present in the final image. @dolfinus is probably right about it being needed for the new JIT.

**Comment by mlh758** [comment]
Closing this for lack of interest.
