### ISSUE TITLE
elixir 1.14 images segfault when running under qemu "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by pgray** [erlef/docker-elixir#61]
We use `docker buildx` to generate `linux/arm64` builds over at [wasmcloud](https://github.com/wasmcloud/wasmcloud-otp) and have been using the official elixir images for a while.

Today, we discovered our version upgrade (`elixir 1.13 -> 1.14`) left us using images that seem broken when running on `x86_64` under qemu:
```
# information about my machine/environment
[pgray@ls ~]$ uname -m
x86_64
[pgray@ls ~]$ export DOCKER_DEFAULT_PLATFORM=linux/arm64
```
`debian-slim`:
```
[pgray@ls ~]$ docker run -it --rm --entrypoint bash elixir:1.13-slim
root@881af09409ab:/# mix --version
Erlang/OTP 24 [erts-12.3.2.7] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1]

Mix 1.13.4 (compiled with Erlang/OTP 24)
root@881af09409ab:/# 
exit

[pgray@ls ~]$ docker run -it --rm --entrypoint bash elixir:1.14-slim
root@776e8f141cf5:/# mix --version
Segmentation fault (core dumped)
root@776e8f141cf5:/# 
exit
```
`alpine`:
```
[pgray@ls ~]$ docker run -it --rm --entrypoint sh elixir:1.13-alpine
/ # mix --version
Erlang/OTP 24 [erts-12.3.2.7] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1]

Mix 1.13.4 (compiled with Erlang/OTP 24)
/ # 

[pgray@ls ~]$ docker run -it --rm --entrypoint sh elixir:1.14-alpine
/ # mix --version
Segmentation fault (core dumped)```

I pulled down `hexpm/elixir:1.14.2-erlang-24.3.4.9-debian-bullseye-20230202-slim` to compare and it works without issue.

**Comment by sando38** [comment]
Hi, please try again with elixir vsn `1.14.4`, as it seems with the recent update to erlang/otp 25.3 segfaults with qemu vanished. At least for different project I experienced segfaults with erlang/otp 25.0 - 25.2.x.

**Comment by pgray** [comment]
So it has... that's weird, but thanks for the notification!

**Comment by brooksmtownsend** [comment]
Hi @sando38 , unfortunately it doesn't seem like using `1.14.4` fully resolved our issue. I was updating one of our related projects and it seems I hit a segfault when running `mix deps.get`, strangely enough.

Here is that PR, I set up a minimal Dockerfile to reproduce that sources from `elixir:1.14.4-slim`

**Comment by sando38** [comment]
Yeah, I saw that @brooksmtownsend . Maybe there is hope now with closing of this issue:
https://gitlab.com/qemu-project/qemu/-/issues/1034

**Comment by pgray** [comment]
awesome news. closing
