### ISSUE TITLE
Unable to pull elixir:1.16.2-slim due to no matching manifest for linux/amd64

### ISSUE THREAD

**Issue by nickjj** [erlef/docker-elixir#94]
I'm running a standard Intel 64-bit CPU and have run a bunch of Elixir versions in the past.

But here's what happens when trying to pull 1.16.2-slim:

```
$ docker pull elixir:1.16.2-slim
1.16.2-slim: Pulling from library/elixir
no matching manifest for linux/amd64 in the manifest list entries
```

It looks like this version is missing a bunch of standard CPU architectures:

![image](https://github.com/erlef/docker-elixir/assets/813219/31f485e7-a42e-4525-9121-4264fc353e55)

1.16.1-slim and earlier works fine because they are built with more CPU architectures:

![image](https://github.com/erlef/docker-elixir/assets/813219/cd08eb21-9831-4096-974f-76344e969d07)

**Comment by getong** [comment]
It is ok now.

**Comment by nickjj** [comment]
It's still missing a number of standard CPU architectures at the time of this comment, here's a new screenshot:

![image](https://github.com/erlef/docker-elixir/assets/813219/96412eec-a79e-462f-bc0f-cbe95724c822)

This is based on: https://hub.docker.com/_/elixir/tags?page=1&name=1.16.2-slim

**Comment by nickjj** [comment]
It looks like it's been addressed ~5 hours after the previous comment:

![image](https://github.com/erlef/docker-elixir/assets/813219/b58e2683-5673-4561-b039-0127de781869)
